spring:
  application:
    name: user-manager
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      connection-timeout: ${DB_CONNECTION_TIMEOUT}
      maximum-pool-size: ${DB_POOL_SIZE}
  jpa:
    show-sql: ${SHOW_SQL}
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: ${POSTGRES_SCHEMA}
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  liquibase:
    enabled: true
    change-log: db/changelog.xml
    default-schema: ${POSTGRES_SCHEMA}
    liquibase-schema: ${POSTGRES_SCHEMA}
  mvc: 
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  forward-headers-strategy: FRAMEWORK
  servlet:
    context-path: /api
management:
  endpoints:
    web:
      exposure:
        include: health
springdoc:
   api-docs.path: /api-docs
logging:
  level:
    root: ${LOGGING_LEVEL}
